apiVersion: openebs.io/v1alpha1
kind: CASTemplate
metadata:
  name: cast-standard-0.7.0
spec:
  defaultConfig:
  - name: VolumeMonitor
    enabled: "true"
  - name: ControllerImage
    value: openebs/cstor:0.5.0
  - name: ReplicaCount
    value: "1"
  - name: StoragePool
    value: ssd
  run:
    taskNamespace: default
    tasks:
    - task: cstor-volume-create-put-service-0.7.0
      id: vsvc
    - task: cstor-volume-create-put-cr-0.7.0
      id: vcr
    - task: cstor-volume-create-put-controller-0.7.0
      id: vctrl
    - task: cstor-volume-create-put-replica-cr-0.7.0
      id: vrep
    output:
      task: volume-create-output-0.7.0
