apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-volume-create-put-service-0.7.0
  namespace: default
data:
  meta: |
    runNamespace: {{ .Volume.runNamespace }}
    apiVersion: v1
    kind: Service
    action: put
    queries:
      - alias: objectName
      - alias: clusterIP
          path: |-
            {.spec.clusterIP}
  task: |
    apiVersion: openebs.io/v1alpha1
    kind: Service
    metadata:
      labels:
        openebs/controller-service: cstor-controller-service
        openebs.io/controller-service: cstor-controller-svc
        openebs.io/storage-engine-type: cstor
        openebs/volume-provisioner: cstor
        vsm: {{ .Volume.owner }}
        openebs.io/pv: {{ .Volume.owner }}
      name: {{ .Volume.owner }}-ctrl-svc
    spec:
      ports: #check for ports with moteesh
      - name: iscsi
        port: 3260
        protocol: TCP
        targetPort: 3260
      selector:
        openebs/controller: cstor-controller
        vsm: {{ .Volume.owner }}
        openebs.io/controller: cstor-controller
        openebs.io/pv: {{ .Volume.owner }}
