apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-volume-create-put-cr-0.7.0
  namespace: default
data:
  meta: |
    runNamespace: {{ .Volume.runNamespace }}
    apiVersion: openebs.io/v1alpha1
    kind: CStorVolume
    action: put
    queries:
    - alias: cstorid
      path: |-
        {.metadata.uid}
    - alias: objectName
  task: |
    apiVersion: openebs.io/v1alpha1
    kind: CStorVolume
    metadata:
      name: {{ .Volume.owner }}
    spec:
      cStorControllerIP: {{ .TaskResult.vsvc.clusterIP }}
      volumeName: {{ .Volume.owner }}
      volumeId: {{ .Volume.uid }}
      capacity: {{ .Volume.capacity }}
      status: init
