apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: default-openebs-pvc-749720879
  name: default-openebs-pvc-749720879
  namespace: openebs
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: default-openebs-pvc-749720879
  sessionAffinity: None
  type: ClusterIP
