apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-maya-operator
  namespace: default
---
# Define Role that allows operations on K8s pods/deployments
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-maya-operator
rules:
- apiGroups: ["*"]
  resources: [ "cstorvolumes","events"]
  verbs: ["*" ]
---
# Bind the Service Account with the Role Privileges.
# TODO: Check if default account also needs to be there
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-maya-operator
  namespace: default
subjects:
- kind: ServiceAccount
  name: default-maya-operator
  namespace: default
- kind: User
  name: system:serviceaccount:default:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: default-maya-operator
  apiGroup: rbac.authorization.k8s.io

