apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-pool-default-0.7.0"
      - name: ReplicaCount
        value: "1"
      - name: PVCServiceAccountNamea
        value: "user-service-account"
    openebs.io/cas-type: cstor
  name: openebs-cstor-default-0.7.0
provisioner: openebs.io/provisioner-iscsi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openebs-pvc
  labels:
    openebs.io/target-affinitya: nginx
spec:
  storageClassName: openebs-cstor-default-0.7.0
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5G
---
