apiVersion: v1
kind: ConfigMap
metadata:
  name: volume-read-list-controller-service-0.7.0
  namespace: default
data:
  meta: |
    runNamespace: {{ .Volume.runNamespace }}
    apiVersion: v1
    kind: Service
    action: list
    options: |-
      labelSelector: openebs.io/controller-service=cstor-controller-svc,openebs.io/pv={{ .Volume.owner }}
    queries:
    - alias: objectName
      path: |-
        {.kind}
    - alias: clusterIP
      path: |-
        {.items[*].spec.clusterIP}
