apiVersion: v1
kind: ConfigMap
metadata:
  name: volume-read-list-cvr-0.7.0
  namespace: default
data:
  meta: |
    runNamespace: {{ .Volume.runNamespace }}
    apiVersion: v1
    kind: CStorVolumeReplica
    action: list
    options: |-
      labelSelector: cstorvolumereplica.openebs.io/pvc-name: {{ .Volume.owner }}
    queries:
    - alias: objectName
      path: |-
        {.items[0].kind}
    - alias: capacity
      path: |-
        {.items[*].spec.capacity}
    - alias: cStorPoolName
      path: |-
        {.items[*].metadata.labels.cstorpool\.openebs\.io/name}
    - alias: status
      path: |-
        {.items[*].status.phase}
