apiVersion: v1
kind: ConfigMap
metadata:
  name: volume-delete-list-cstorvolumereplica-0.7.0
  namespace: default
data:
  meta: |
    id: deletelistcvr
    runNamespace: {{ .Volume.runNamespace }}
    apiVersion: openebs.io/v1alpha1
    kind: CStorVolumeReplica
    action: list
    options: |-
      labelSelector: openebs.io/pv={{ .Volume.owner }}
  post: |
    {{- $cvrs := jsonpath .JsonResult `{range .items[*]}pkey=cvrs {@.metadata.name}="";{end}` | trim | default "" | splitList ";" -}}
    {{- $cvrs | notFoundErr "cstor volume replica not found" | saveIf "deletelistcvr.notFoundErr" .TaskResult | noop -}}
    {{- $cvrs | asKeyMap "cvrlist" .ListItems | noop -}}
