apiVersion: v1
kind: ConfigMap
metadata:
  name: volume-delete-output-0.7.0
  namespace: default
data:
  meta: |
    id: deleteoutput
    action: output
    kind: CASVolume
    apiVersion: v1alpha1
  task: |
    kind: CASVolume
    apiVersion: v1alpha1
    metadata:
      name: {{ .Volume.owner }}
