apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-volume-create-list-pool-0.7.0
  namespace: default
data:
  meta: |
    id: cvolcreatelistpool
    runNamespace: {{ .Volume.runNamespace }}
    apiVersion: openebs.io/v1alpha1
    kind: CStorPool
    action: list
    options: |-
      labelSelector: spc.openebs.io/uid={{ .Config.spc.value }}
  post: |
    {{- $poolsList := jsonpath .JsonResult `{range .items[*]}pkey=pools {@.metadata.uid}={@.metadata.name};{end}` | trim | default "" | splitList ";" -}}
    {{- $poolsList | asKeyMap "cvolPoolList" .ListItems | noop -}}
