apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-volume-create-put-service-0.7.0
  namespace: default
data:
  meta: |
    apiVersion: v1
    kind: Service
    action: put
    id: cvolcreateputsvc
    runNamespace: {{ .Volume.runNamespace }}
  post: |
    {{- jsonpath .JsonResult "{.metadata.name}" | trim | saveAs "cvolcreateputsvc.objectName" .TaskResult | noop -}}
    {{- jsonpath .JsonResult "{.spec.clusterIP}" | trim | saveAs "cvolcreateputsvc.clusterIP" .TaskResult | noop -}}
  task: |
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        openebs/controller-service: cstor-controller-service
        openebs.io/controller-service: cstor-controller-svc
        openebs.io/storage-engine-type: cstor
        openebs/volume-provisioner: cstor
        vsm: {{ .Volume.owner }}
        openebs.io/pv: {{ .Volume.owner }}
      name: {{ .Volume.owner }}-ctrl-svc
    spec:
      ports: #check for ports with moteesh
      - name: cstor-iscsi
        port: 3260
        protocol: TCP
        targetPort: 3260
      selector:
        openebs/controller: cstor-controller
        vsm: {{ .Volume.owner }}
        openebs.io/controller: cstor-controller
        openebs.io/pv: {{ .Volume.owner }}
