apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-volume-create-put-controller-0.7.0
  namespace: default
data:
  meta: |
    runNamespace: {{ .Volume.runNamespace }}
    apiVersion: extensions/v1beta1
    kind: Deployment
    action: put
    id: cvolcreateputctrl
  post: |
    {{- jsonpath .JsonResult ".metadata.name" | trim | saveAs "cvolcreateputctrl.objectName" .TaskResult | noop -}}
  task: |
    {{- $isMonitor := .Config.VolumeMonitor.enabled | default "true" | lower -}}
    {{- $monitorVal := .Config.VolumeMonitor.value | default "openebs/m-exporter:0.5.0" -}}
    apiVersion: extensions/v1beta1
    Kind: Deployment
    metadata:
      name: {{ .Volume.owner }}-ctrl
      labels:
        app: cstor-volume-manager
        openebs.io/storage-engine-type: cstor
        openebs/volume-provisioner: cstor
        openebs/controller: cstor-controller
        openebs.io/controller: cstor-controller
        vsm: {{ .Volume.owner }}
        openebs.io/pv: {{ .Volume.owner }}
      annotations:
        {{- if eq $isMonitor "true" }}
        openebs.io/volume-monitor: "true"
        {{- end}}
        openebs.io/volume-type: cstor
    spec:
      replicas: 1
      selector:
        matchLabels:
          {{- if eq $isMonitor "true" }}
          monitoring: volume_exporter_prometheus
          {{- end}}
          openebs.io/controller: cstor-controller
          openebs/controller: cstor-controller
          openebs.io/pv: {{ .Volume.owner }}
          vsm: {{ .Volume.owner }}
          app: cstor-volume-manager
      template:
        metadata:
          labels:
            {{- if eq $isMonitor "true" }}
            monitoring: volume_exporter_prometheus
            {{- end}}
            openebs.io/controller: cstor-controller
            openebs/controller: cstor-controller
            openebs.io/pv: {{ .Volume.owner }}
            vsm: {{ .Volume.owner }}
            app: cstor-volume-manager
        spec:
          containers:
          - image: {{ .Config.ControllerIstgtImage.value }}
            name: cstor-istgt
            ports:
            - containerPort: 3260
              protocol: TCP
            securityContext:
              privileged: true
            volumeMounts:
            - name: sockfile
              mountPath: /var/run
            - name: conf
              mountPath: /usr/local/etc/istgt
            - name: dummyfile
              mountPath: /tmp/cstor

          {{- if eq $isMonitor "true" }}
          - image: {{ $monitorVal }}
            name: maya-volume-exporter
            args:
            - -c=http://127.0.0.1:9501
            command:
            - maya-volume-exporter
            ports:
            - containerPort: 9500
              protocol: TCP
          {{- end}}

          - name: cstor-volume-mgmt
            image: {{ .Config.ControllerMgmtImage.value }}
            imagePullPolicy: Always
            ports:
            - containerPort: 80
            env:
            - name: cstorid
              value: {{ .TaskResult.cvolcreateputvolume.cstorid }}
            securityContext:
              privileged: true
            volumeMounts:
            - name: sockfile
              mountPath: /var/run
            - name: conf
              mountPath: /usr/local/etc/istgt
            - name: dummyfile
              mountPath: /tmp/cstor

          volumes:
          - name: sockfile
            emptyDir: {}
          - name: conf
            emptyDir: {}
          - name: dummyfile
            emptyDir: {}
