apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-volume-create-put-replica-0.7.0
  namespace: default
data:
  meta: |
    runNamespace: {{ .Volume.runNamespace }}
    apiVersion: openebs.io/v1alpha1
    kind: CStorVolumeReplica
    action: put
    id: cstorvolumecreatereplica
    repeatWith:
      resources:
      {{- range $k, $v := .ListItems.cvolPoolList.pools }}
      - {{ $k }} #retrieving only key
      {{- end }}
  task: |
    kind: CStorVolumeReplica
    apiVersion: openebs.io/v1alpha1
    metadata:
      name: cstorvolumereplica-{{ .ListItems.currentRepeatResource }}
      labels:
        cstorpool.openebs.io/name: {{ pluck .ListItems.currentRepeatResource .ListItems.cvolPoolList.pools | first }}
        cstorpool.openebs.io/uid: {{ .ListItems.currentRepeatResource }}
        cstorvolume.openebs.io/uid: {{ .TaskResult.cvolcreateputvolume.cstorid }}
        cstorvolumereplica.openebs.io/pvc-name: {{ .Volume.owner }}
        openebs.io/pv: {{ .Volume.owner }}
        # finalizers: ["cstorvolumereplica.openebs.io/finalizer"]
    spec:
      capacity: {{ .Volume.capacity }}
      cStorControllerIP: {{ .TaskResult.cvolcreateputsvc.clusterIP }}
    status:
      phase: init
  post: |
    {{- jsonpath .JsonResult "{metadata.name}" | trim | saveAs "cstorvolumecreatereplica.objectName" .TaskResult | noop -}}
