apiVersion: v1
kind: ConfigMap
metadata:
  name: volume-create-output-0.7.0
  namespace: default
data:
  meta: |
    action: output
    kind: CASVolume
    apiVersion: v1alpha1
  task: |
    kind: CASVolume
    apiVersion: v1alpha1
    metadata:
      name: {{ .Volume.owner }}
      annotations:
        vsm.openebs.io/iqn: iqn.2016-09.com.openebs.cstor:{{ .Volume.owner }}
        vsm.openebs.io/replica-count: {{ .Config.ReplicaCount.value }}
        vsm.openebs.io/volume-size: {{ .Volume.capacity }}
        capacity: {{ .Volume.capacity }}
